#!/usr/bin/env node

// Diffs the current operation mapping (provider-dev/config/all_services.csv)
// against the predecessor provider's method inventory
// (provider-dev/config/predecessor_methods.csv, written once by
// snapshot_predecessor.mjs from the last v1 commit) by (path, verb), and
// writes the Breaking Changes section of the README between the
// BEGIN:BREAKING-CHANGES / END:BREAKING-CHANGES markers. Deterministic;
// run after every mapping change (`make compare`).
//
// Dispositions:
//   carried  - same service.resource, method renamed or not
//   moved    - same operation now lives on a different service.resource
//   retired  - the predecessor method's operation is no longer in the spec,
//              or is reason-coded skip in the new mapping
//   added    - new operations with no predecessor (counted only)
//
// Usage: node provider-dev/scripts/compare_predecessor.mjs [--check]

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { parseCsv } from './lib/spec_helpers.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const currentPath = path.join(repoRoot, 'provider-dev', 'config', 'all_services.csv');
const predecessorPath = path.join(repoRoot, 'provider-dev', 'config', 'predecessor_methods.csv');
const readmePath = path.join(repoRoot, 'README.md');
const checkOnly = process.argv.includes('--check');

const cur = parseCsv(fs.readFileSync(currentPath, 'utf8'));
const cc = Object.fromEntries(cur[0].map((h, i) => [h, i]));
const current = new Map();
for (const r of cur.slice(1)) {
  current.set(`${r[cc.path]}::${r[cc.verb]}`, {
    service: r[cc.filename].replace(/\.yaml$/, ''), resource: r[cc.stackql_resource_name], method: r[cc.stackql_method_name], sqlVerb: r[cc.stackql_verb]
  });
}
const pred = parseCsv(fs.readFileSync(predecessorPath, 'utf8'));
const pc = Object.fromEntries(pred[0].map((h, i) => [h, i]));

const carried = [], moved = [], retired = [];
const resourceMap = new Map(); // old service.resource -> Set(new service.resource)
for (const r of pred.slice(1)) {
  const key = `${r[pc.path]}::${r[pc.verb]}`;
  const oldFq = `${r[pc.service]}.${r[pc.resource]}`;
  const now = current.get(key);
  const row = { old: `${oldFq}.${r[pc.method]}`, oldVerb: r[pc.sql_verb], path: `${r[pc.verb].toUpperCase()} ${r[pc.path]}` };
  if (!now || now.resource === 'skip_this_resource') {
    retired.push({ ...row, reason: !now ? 'operation no longer in the vendor spec' : 'skipped in this build (see all_services.csv)' });
    continue;
  }
  const newFq = `${now.service}.${now.resource}`;
  row.new = `${newFq}.${now.method}`;
  row.newVerb = now.sqlVerb;
  if (!resourceMap.has(oldFq)) resourceMap.set(oldFq, new Set());
  resourceMap.get(oldFq).add(newFq);
  if (newFq === oldFq) carried.push(row); else moved.push(row);
}
const added = [...current.values()].filter((v) => v.resource !== 'skip_this_resource').length - carried.length - moved.length;

const renamedResources = [...resourceMap.entries()].filter(([o, n]) => !(n.size === 1 && n.has(o))).sort();
const lines = [];
lines.push('<!-- BEGIN:BREAKING-CHANGES (generated by compare_predecessor.mjs - do not edit) -->');
lines.push('');
lines.push('### Breaking changes from the previous provider release');
lines.push('');
lines.push(`Every method of the previous release (${pred.length - 1} methods across ${new Set(pred.slice(1).map((r) => r[pc.service])).size} services) is dispositioned against this build by operation (path and HTTP verb): ${carried.length} carried on the same resource, ${moved.length} moved to a renamed or restructured resource, ${retired.length} retired; ${added} operations are new to this release. The previous provider version stays available in the registry for pinning.`);
lines.push('');
lines.push('**Method names.** Operation-derived method names (`listUsers`, `getUser`, `createUser`) become resource-scoped names (`list`, `get`, `create`, `update`, `delete`) on every carried resource, and lifecycle operations become `EXEC` methods on the resource they act on (`users.unlock`, `partitions.decommission`, `scheduled_views.pause`) instead of separate non-selectable resources. Columns and `WHERE` / `INSERT` keys are now `snake_case` (`firstName` -> `first_name`); nested JSON values keep the wire casing.');
lines.push('');
lines.push('**Renamed or restructured resources** (previous -> this release):');
lines.push('');
lines.push('| Previous resource | This release |');
lines.push('|---|---|');
for (const [o, n] of renamedResources) lines.push(`| \`${o}\` | ${[...n].sort().map((x) => `\`${x}\``).join(', ')} |`);
lines.push('');
if (retired.length > 0) {
  lines.push('**Retired methods** (reason-coded):');
  lines.push('');
  for (const r of retired.sort((a, b) => a.old.localeCompare(b.old))) lines.push(`- \`${r.old}\` (${r.path}) - ${r.reason}`);
  lines.push('');
}
lines.push('<!-- END:BREAKING-CHANGES -->');
const block = lines.join('\n');

const readme = fs.existsSync(readmePath) ? fs.readFileSync(readmePath, 'utf8') : '';
const re = /<!-- BEGIN:BREAKING-CHANGES[\s\S]*?<!-- END:BREAKING-CHANGES -->/;
if (!re.test(readme)) {
  console.error('README.md has no BEGIN:BREAKING-CHANGES / END:BREAKING-CHANGES markers');
  process.exit(1);
}
const updated = readme.replace(re, block);
if (checkOnly) {
  if (updated !== readme) { console.error('README Breaking Changes section is out of date - run npm run compare-predecessor'); process.exit(1); }
  console.log('compare_predecessor: README Breaking Changes section is current');
} else {
  fs.writeFileSync(readmePath, updated);
  console.log(`compare_predecessor: ${carried.length} carried, ${moved.length} moved, ${retired.length} retired, ${added} added; ${renamedResources.length} resource renames written to README.md`);
}
